function SpawnRegions()
	return {
		{ name = "Muldraugh, KY", file = "media/maps/Muldraugh, KY/spawnpoints.lua" },
		{ name = "Riverside, KY", file = "media/maps/Riverside, KY/spawnpoints.lua" },
		{ name = "Rosewood, KY", file = "media/maps/Rosewood, KY/spawnpoints.lua" },
		{ name = "West Point, KY", file = "media/maps/West Point, KY/spawnpoints.lua" },
		{ name = "carhouse", file = "media/maps/carhouse/spawnpoints.lua" },
		{ name = "Xonics Mega Mall", file = "media/maps/Xonics Mega Mall/spawnpoints.lua" },
		{ name = "Xonics Mega Mall Exterior", file = "media/maps/Xonics Mega Mall Exterior/spawnpoints.lua" },
		{ name = "Xonics Mega Mall Interior", file = "media/maps/Xonics Mega Mall Interior/spawnpoints.lua" },
		{ name = "Xonics Mega Mall Roof", file = "media/maps/Xonics Mega Mall Roof/spawnpoints.lua" },
		{ name = "Chinatown", file = "media/maps/Chinatown/spawnpoints.lua" },
		{ name = "BedfordFalls", file = "media/maps/BedfordFalls/spawnpoints.lua" },
		{ name = "North", file = "media/maps/North/spawnpoints.lua" },
		{ name = "South", file = "media/maps/South/spawnpoints.lua" },
		{ name = "West", file = "media/maps/West/spawnpoints.lua" },
		{ name = "Eerie A", file = "media/maps/Eerie A/spawnpoints.lua" },
		{ name = "Eerie B", file = "media/maps/Eerie B/spawnpoints.lua" },
		{ name = "Eerie C", file = "media/maps/Eerie C/spawnpoints.lua" },
		{ name = "Eerie Country", file = "media/maps/Eerie Country/spawnpoints.lua" },
		{ name = "Eerie D", file = "media/maps/Eerie D/spawnpoints.lua" },
		{ name = "Fort Knox linked to Eerie Country", file = "media/maps/Fort Knox linked to Eerie Country/spawnpoints.lua" },
		{ name = "Near Fort Knox", file = "media/maps/Near Fort Knox/spawnpoints.lua" },
		{ name = "To Bedford Falls", file = "media/maps/To Bedford Falls/spawnpoints.lua" },
		{ name = "To Eerie Country", file = "media/maps/To Eerie Country/spawnpoints.lua" },
		{ name = "Fort Knox, KY by Woldren", file = "media/maps/Fort Knox, KY by Woldren/spawnpoints.lua" },
		{ name = "FortRedstone", file = "media/maps/FortRedstone/spawnpoints.lua" },
		{ name = "Otr", file = "media/maps/Otr/spawnpoints.lua" },
		{ name = "Over the River - Secondary Route", file = "media/maps/Over the River - Secondary Route/spawnpoints.lua" },
		{ name = "RavenCreek", file = "media/maps/RavenCreek/spawnpoints.lua" },
		{ name = "From Bedford Falls to Fort Knox", file = "media/maps/From Bedford Falls to Fort Knox/spawnpoints.lua" },
	}
end
